[project]
name = "kimi-k2-crewai"
version = "0.1.0"
description = "Local CrewAI + MCP + vLLM (Kimi K2) setup"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "vllm>=0.6.2", # vLLM for running Kimi K2
    "crewai>=0.36.0", # CrewAI orchestration
    "fastmcp>=0.1.3", # FastMCP server framework
    "playwright>=1.48.0", # Browser automation for MCP
    "openai>=1.50.2", # OpenAI-compatible client
    "huggingface-hub[cli]>=0.35.0",
]

[tool.uv]
# optional: ensures uv syncs with GPU / CUDA libs properly
